### ISSUE TITLE
Problem when import dot with attribute

### ISSUE THREAD

**Issue by u1Ys** [h-ohsaki/graph-tools#1]
https://github.com/h-ohsaki/graph-tools/blob/ec8a23df73efd2e39b5802f8aad5cdffb0e4fa2f/graph_tools/__init__.py#L1343

The current graph-tools import all values of all attributes (e.g., *[weight = "2"]*) as string.

However, the value of attribute is often *int* or *float*.

In the current code, when import a dot with weight and use dijkstra,

https://github.com/h-ohsaki/graph-tools/blob/ec8a23df73efd2e39b5802f8aad5cdffb0e4fa2f/graph_tools/__init__.py#L471-L477

calculate *int + str*.

Quick hack is,

```python
                attrs[akey] = float(aval.replace('\"', ''))
```

**Comment by h-ohsaki** [comment]
Thank you for your suggestion.  In version 1.3, only `weight' attributes are converted to float.
